Repository rapidcore/rapidcore, pull requests merged in 2020-12, with the labels that each got.

#171 Upgrade to stackexchange redis 2.*
  src/redis/main/rapidcore.redis.csproj
Labels: breaking change

#173 Use redis connection pool for Redis Lock Provider
  src/core/main/Globalization/Iso4217Currencies.cs
  src/core/main/IO/FileSystem/DotNetFileSystemProvider.cs
  src/core/main/IO/FileSystem/SftpClient.cs
  src/core/main/IO/FileSystem/SftpFileSystemProvider.cs
  src/core/main/Security/RandomNumberGeneratorGuid.cs
  src/mongo/test-functional/MongoDbConnectionTests.cs
  src/mongo/test-functional/MongoDbConnection_GetCollection_Tests.cs
  src/mongo/test-functional/MongoDbConnection_Insert_Tests.cs
  src/mongo/test-functional/MongoManagerTests/EnsureIndexesWithCustomCollectionNameTests.cs
  src/redis/main/Locking/RedisDistributedAppLockProvider.cs
  src/redis/main/rapidcore.redis.csproj
  src/redis/test-functional/Locking/RedisDistributedAppLockProviderTest.cs
  src/redis/test-functional/Migration/MigrationTests.cs
  src/redis/test-functional/Migration/YoloMigrationRunnerTests .cs
  src/sqlserver/main/Locking/SqlServerDistributedAppLock.cs
  src/sqlserver/main/Locking/SqlServerDistributedAppLockProvider.cs
  src/test-unit/Redis/Locking/RedisDistributedAppLockProviderTest.cs
  src/xunit/main/Logging/XunitOutputLogger.cs
  src/xunit/main/Logging/XunitOutputLoggerProvider.cs
  src/xunit/main/Logging/XunitOutputLoggerProviderExtension.cs
Labels: breaking change, feature request

#178 Throw exception if given instance that cannot be traversed
  docs/RapidCore.Reflection/InstanceTraverser.md
  src/core/main/Reflection/InstanceTraversalException.cs
  src/core/main/Reflection/InstanceTraverser.cs
  src/test-unit/Core/Reflection/InstanceTraverserTests/InstanceTraverser_BasicTests.cs
Labels: bug

#179 Depend on latest StackExchange.Redis.Extensions.Core 6.x series
  src/redis/main/Locking/RedisDistributedAppLock.cs
  src/redis/main/Locking/RedisDistributedAppLockProvider.cs
  src/redis/main/rapidcore.redis.csproj
  src/test-unit/Redis/Locking/RedisDistributedAppLockProviderTest.cs
  src/test-unit/Redis/Locking/RedisDistributedAppLockTest.cs
Labels: breaking change, feature request

#180 Add props to tell whether locks have been taken immediately
  src/core/main/Locking/IDistributedAppLock.cs
  src/core/main/Locking/NoopDistributedAppLock.cs
  src/redis/main/Locking/RedisDistributedAppLock.cs
  src/redis/test-functional/Locking/RedisDistributedAppLockProviderTest.cs
  src/sqlserver/main/Locking/SqlServerDistributedAppLock.cs
  src/sqlserver/test-functional/Locking/SqlServerDistributedAppLockProviderTests.cs
  src/test-unit/Redis/Locking/RedisDistributedAppLockTest.cs
Labels: breaking change, feature request
